### ISSUE TITLE
кнопка submit маленькая и расположение странное

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/FlutterTurnip#14]
![image](https://user-images.githubusercontent.com/100202857/177321784-e28e1ed6-2f4e-45bc-874f-2c81547941e6.png)

**Comment by ramilsalihar** [comment]
Положение исправлено.

![image](https://user-images.githubusercontent.com/68570136/178986415-7bff6760-09ee-4ce7-8390-088667da0819.png)
