### ISSUE TITLE
унифицировать название "выполненные/невыполненные" и подобные слова

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/FlutterTurnip#15]
унифицировать название "выполненные/невыполненные" и подобные слова, поскольку в инструкциях это важно и придется писать разные инструкции к сайту, приложению и т.д.

**Comment by ramilsalihar** [comment]
Можно уточнить что именно вы имеете ввиду. Не совсем понял что это значит(.

**Comment by aTNa-Lab** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/23186022/178428214-b0747ee3-b366-4fc5-9626-00b29e3529f8.png">
открытые/закрытые поменяй на выполненные/невыполненные

**Comment by ramilsalihar** [comment]
Сделано!
