### ISSUE TITLE
система должна быть на кр, англ и ру. вместо "система" должно быть "язык"

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/FlutterTurnip#17]
![image](https://user-images.githubusercontent.com/100202857/177323418-06eb608c-d205-407d-b2a3-020d0b1595cf.png)
а еще лучше сразу писать English, кыргызча, русский

**Comment by ramilsalihar** [comment]
Добавил кыргызский язык. 
Поменял слово "Система" => "Язык".
При удалении слова Язык, выходит ошибка поэтому оставил как есть.
