### ISSUE TITLE
текст в формах жирный и размазанный

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/FlutterTurnip#18]
<img width="596" alt="image_2022-07-05_17-36-22" src="https://user-images.githubusercontent.com/100202857/177323618-8523bb00-0d7c-4e43-8970-a5b6bd9449d2.png">
первое поле норм, а следующие уже рамазанные. а еще шрифт жирный, а должен быть нежирным

**Comment by ramilsalihar** [comment]
Исправил.
Жирным оставил только заголовки.

![image](https://user-images.githubusercontent.com/68570136/178983996-f33ad327-f64b-45be-ace8-8dfb41af7035.png)
