### ISSUE TITLE
Буквы слипаются

### ISSUE THREAD

**Issue by bbekaa** [KloopMedia/FlutterTurnip#22]
![image](https://user-images.githubusercontent.com/100202857/177325163-7b8d769a-3bb3-46c3-bba0-c3fee82890bf.png)

**Comment by ramilsalihar** [comment]
Добавил FittedBox, теперь оно не сливаться. 
![image](https://user-images.githubusercontent.com/68570136/178424942-f24c67a2-f81b-4d3e-b25c-ffbd578cbc57.png)
