### ISSUE TITLE
Серое поле после обновления страницы доступных в Okutool

### ISSUE THREAD

**Issue by Bagymdat** [KloopMedia/FlutterTurnip#29]
<img width="1440" alt="Screen Shot 2022-07-08 at 12 38 59" src="https://user-images.githubusercontent.com/31596354/177932325-012d8ba6-5efa-4467-8fe3-7afe814913fc.png">

**Comment by aTNa-Lab** [comment]
Это проблема в браузерной версии. В ближайшее время исправлять не будем.
