### ISSUE TITLE
таски не отправляются в цепи вики-упражнения campaign 7 chain 40 task ID 1687

### ISSUE THREAD

**Issue by Bagymdat** [KloopMedia/FlutterTurnip#31]
<img width="1440" alt="Screen Shot 2022-07-08 at 12 54 27" src="https://user-images.githubusercontent.com/31596354/177934727-f81b0eee-dc57-4ce0-99b5-cf2e19ffc775.png">
показывает processing data и не сохраняет кейс

**Comment by aTNa-Lab** [comment]
#11
