### ISSUE TITLE
текст внутри таск полей больше текста вопроса самого таска

### ISSUE THREAD

**Issue by Bagymdat** [KloopMedia/FlutterTurnip#70]
<img width="1440" alt="Screen Shot 2022-10-10 at 16 35 32" src="https://user-images.githubusercontent.com/31596354/194847542-86076ad2-39a5-423a-a010-d3de0b7f74ef.png">

**Comment by ramilsalihar** [comment]
![image](https://user-images.githubusercontent.com/68570136/197986710-e443adac-ad89-4b49-ba77-8354d61a2d10.png)
Исправлено
